<html>
<head>
<link rel="stylesheet"
	href="<?php echo $this->basePath() . '/css/style-iframe.css'?>"
	type="text/css" media="screen">
</head>
<body>
	<h3 class="box-head">Motivation</h3>
	<div class="box-body">
		<p>Online reviews are posted by people who have experience of using
			the products/services. A review usually consists of a rating score
			and a piece of comment describing the feedback of using the
			product/service. More and more people are relying on online reviews
			when evaluating the quality of products, hotels, restaurants, and
			even vacation packages. The reason includes that the description of
			the product/service may not be accurate, and that the other clues
			such as touching and trying out may not be available. The online
			review systems, also referred to as online reputation systems, allow
			users to post reviews for products/services, and aggregate these
			reviews to assign each product/service with a reputation score that
			indicates the quality (e.g. number of stars in Amazon). Online
			reputation systems can help people evaluate the quality of
			products/services before transactions, and hence greatly reduce the
			risks of people's buying behaviors.</p>
		<p>However, not all the reviews are honest. Driven by the huge profits
			of online markets, attacks that attempt to mislead users' buying
			decisions through dishonest reviews are gaining popularity. Sellers
			at the online marketplace boost their reputation by trading with
			collaborators. Firms post biased reviews to praise their own products
			or bad-mouth their competitors' products. Review manipulation can
			overly inflate or deflate products' reputation scores, crash users'
			confidence in online reputation systems, eventually undermine
			reputation-centric online businesses and lead to economic loss.
			Particularly, there are some situations in which the review
			manipulation is even more damaging. For example, in Black Friday,
			people may have to make a rush decision because the 'unusual'
			discount will expire quickly. Another example is that the hotels and
			restaurants cannot be returned after people using them.</p>
	</div>

	<h3 class="box-head">ReviewSec Project</h3>
	<div class="box-body">
		<p>After learning quite a lot of fundamental issues of review
			manipulation, we began to build this online tool using our expertise.</p>
	</div>

</body>
</html>
